export const configs =
    [
        {
            name: "Pulse",
            bgColor: "#ffffff",
            bgAlpha: 0,
            radial: true,
            ledBars: true,
            showScaleX: false,
            showScaleY: false,
            linearBoost: 3,
            minFreq: 1000,
            maxFreq: 8000,
            barSpace: 0,
            radius: 0,
            spinSpeed: 1.5,
            frequencyScale: "log",
            channelLayout: "dual-horizontal",
            mode: 10,
            gradientLeft: "prism",
            gradientRight: "classic",
            maxDecibels: -25,
            minDecibels: -90,
        },
        {
            name: "crackles",
            bgColor: "#ffffff",
            bgAlpha: 0,
            radial: true,
            ledBars: true,
            showScaleX: false,
            showScaleY: false,
            linearBoost: 8,
            minFreq: 60,
            maxFreq: 12000,
            barSpace: 0,
            gradientLeft: "prism",
            radius: 0,
            spinSpeed: 5,
            frequencyScale: "mel",
        },
        {  
            name: "Spectrum",
            "alphaBars": false,
            "ansiBands": false,
            "barSpace": 0,
            "bgAlpha": "1",
            "channelLayout": "single",
            "colorMode": "bar-index",
            "fftSize": 2048,
            "fillAlpha": "0.2",
            "frequencyScale": "log",
            "gradient": "prism",
            "ledBars": false,
            "linearAmplitude": false,
            "linearBoost": 1,
            "lineWidth": 1,
            "loRes": false,
            "lumiBars": false,
            "maxDecibels": -25,
            "maxFPS": 0,
            "maxFreq": 10000,
            "minDecibels": -90,
            "minFreq": 1000,
            "mirror": 1,
            "mode": 10,
            "noteLabels": false,
            "outlineBars": false,
            "overlay": false,
            "peakLine": false,
            "radial": true,
            "radialInvert": false,
            "radius": 0,
            "reflexAlpha": "1",
            "reflexBright": "2",
            "reflexFit": true,
            "reflexRatio": 0,
            "roundBars": true,
            "showBgColor": false,
            "showFPS": false,
            "showPeaks": true,
            "showScaleX": false,
            "showScaleY": false,
            "smoothing": 0.5,
            "spinSpeed": 1,
            "splitGradient": false,
            "trueLeds": false,
            "useCanvas": true,
            "volume": 1,
            "weightingFilter": "A"
          },
          { 
            name: "Waveform",
            bgColor: "#ffffff",
            bgAlpha: 0,
            radial: true,
            ledBars: true,
            showScaleX: false,
            showScaleY: false,
            linearBoost: 3,
            minFreq: 60,
            maxFreq: 12000,
            barSpace: 0,
            radius: 0,
            spinSpeed: 1.5,
            frequencyScale: "log",
            channelLayout: "dual-horizontal",
            mode: 0,
            gradientLeft: "prism",
            gradientRight: "rainbow",
            maxDecibels: -25,
            minDecibels: -90,
          }
    ];