export const configs =
  [
    {
        name: "Pulse",
        bgColor: "#ffffff",
        bgAlpha: 0,
        radial: true,
        ledBars: true,
        showScaleX: false,
        showScaleY: false,
        linearBoost: 3,
        minFreq: 1000,
        maxFreq: 8000,
        barSpace: 0,
        radius: 0,
        spinSpeed: 1.5,
        frequencyScale: "log",
        channelLayout: "dual-horizontal",
        mode: 10,
        gradientLeft: "prism",
        gradientRight: "classic",
        maxDecibels: -25,
        minDecibels: -90,
    },
    {
        name: "Pulse22",
        bgColor: "#ffffff",
        bgAlpha: 0,
        radial: true,
        ledBars: true,
        showScaleX: false,
        showScaleY: false,
        linearBoost: 3,
        minFreq: 1000,
        maxFreq: 8000,
        barSpace: 0,
        radius: 0,
        spinSpeed: 1.5,
        frequencyScale: "log",
        channelLayout: "dual-horizontal",
        mode: 10,
        gradientLeft: "classic",
        gradientRight: "classic",
        maxDecibels: -25,
        minDecibels: -90,
    },
];